# Generated by Django 3.1.2 on 2020-11-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0002_auto_20201031_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='mtaa',
            new_name='hood',
        ),
    ]
